IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE TYPE = 'U' AND NAME = 'PARCEIRO')
BEGIN
CREATE TABLE PARCEIRO
(
	ID	INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(50)	NOT NULL,
    APELIDO VARCHAR		NULL,
    EMAIL VARCHAR(100)	NULL,
    DATACADASTRO DATETIME	NULL,
    DATANASCIMENTO DATETIME NULL,
    ISATIVO INT	NULL,
	PRIMARY KEY(ID)
)
END
GO

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE TYPE = 'U' AND NAME = 'PERSONAGEM')
BEGIN
CREATE TABLE PERSONAGEM
(
	ID	INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(50)	NOT NULL,
    APELIDO VARCHAR		NULL,
    EMAIL VARCHAR(100)	NULL,
    DATACADASTRO DATETIME	NULL,
    DATANASCIMENTO DATETIME NULL,
    ISATIVO INT	NULL,
	PRIMARY KEY(ID)
)
END
GO

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE TYPE = 'U' AND NAME = 'PERSONAGEMPARCEIRO')
BEGIN
CREATE TABLE PERSONAGEMPARCEIRO
(
	ID_PERSONAGEM INT	NOT NULL,
    ID_PARCEIRO INT NOT NULL,
    ID_DIMENSAO INT NOT NULL,
	PRIMARY KEY (ID_PERSONAGEM,ID_PARCEIRO,ID_DIMENSAO)
)
END
GO

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE TYPE = 'U' AND NAME = 'DIMESAO')
BEGIN
CREATE TABLE DIMESAO
(
	ID	INT		IDENTITY(1,1)	NOT NULL,
	DESCRICAO VARCHAR(100)	NULL,
    LONGITUDE DECIMAL NULL,
    LATITUDE DECIMAL NULL,
    ALTURA DECIMAL NULL,
    PRECISAOH DECIMAL NULL,
    PRECISAOV DECIMAL NULL,
    CARACTERISTICA VARCHAR(100) NULL,
	PRIMARY KEY(ID)
)
END
GO

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE TYPE = 'U' AND NAME = 'VIAGEM')
BEGIN
CREATE TABLE VIAGEM
(
	ID	INT	IDENTITY(1,1)	NOT NULL,
    ID_PERSON_PARC INT NOT NULL,
    ID_DIMENSAO INT NOT NULL,
	DESCRICAO VARCHAR(100) NULL,
    DTH_LOCAL DATETIME NULL,
    DTH_DESTINO DATETIME NULL,
	PRIMARY KEY(ID, ID_PERSON_PARC, ID_DIMENSAO)
)
END
GO